# qiime2
#
# VERSION       2022.2
FROM quay.io/qiime2/core:2022.2
MAINTAINER Allen Chaung summerhill001@gmail.com

#USER 1000:1000

#ENV GALAXY_CONFIG_BRAND deepTools
# The following two lines are optional and can be given during runtime
# with the -e http_proxy='http://yourproxyIP:8080' parameter
#ENV http_proxy 'http://yourproxyIP:8080'
#ENV https_proxy 'http://yourproxyIP:8080'

WORKDIR /workspace

# Expose port 80 (webserver), 21 (FTP server), 8800 (Proxy)
EXPOSE :8888


# Activate the environment, and make sure it's activated:
#RUN conda activate qiime2-2022.2
#RUN conda init
#RUN bash
#RUN sleep 2
#RUN conda update -n base -c defaults conda
#RUN conda activate qiime2-2022.2
#RUN conda install -n qiime2-2022.2 -y -c conda-forge jupyterlab
RUN jupyter serverextension enable --py qiime2 --sys-prefix
#COPY run.py .


# Autostart script that is invoked during container start
CMD ["jupyter","notebook","--NotebookApp.token=''","--NotebookApp.password=''","--ip=0.0.0.0","--allow-root","--port=8888","--no-browser"]

